# Generated by Django 4.2.3 on 2023-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
                ('do_datetime', models.DateTimeField()),
            ],
        ),
    ]
